### ISSUE TITLE
[Task] 🛠️ Security: Configure security analysis: Private Vuln Reporting | Dependabot

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/ibm-skills-ai-colab-sessions#6]
### Task Topic

Other

### Task Description

Configure repository security and analysis using GitHub Secuirty Settings

## Tasks

- [ ] Private vulnerability reporting
- [ ] Dependency graph
- [ ] Automatic dependency submission
- [x] Dependabot
  - [x] Dependabot alerts
    - [x] Dependabot rules
  - [x] Dependabot security updates
  - [x] Grouped security updates
  - [x] Dependabot version updates
  - [x] Dependabot on Actions runners

#### Tools
- [ ] CodeQL analysis
- [ ] Other Tools
  - [ ] Add any third-party 

#### Protection Rules
- [ ] Security alert severity levels: High or Higher
- [ ] Standard alert severity level: Only Errors

### Secret scanning
- [ ] Receive alerts on GitHub for detected secrets, keys, or other tokens.
- [ ] Push protection:  Block commits that contain [supported secrets](https://docs.github.com/code-security/secret-scanning/secret-scanning-patterns#supported-secrets)

### Use Case

Outline:  Security and analysis features help keep your repository secure and updated. 
- Enable these features to perform read-only analysis on your repository.

### Additional Information

- https://github.com/iPoetDev/ibm-skills-ai-colab-sessions/security
- https://github.com/iPoetDev/ibm-skills-ai-colab-sessions/settings/security_analysis

**Comment by iPoetDev** [comment]
✅ Initailise Dependabot on a weekly basis
